version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe
    image: camunda/zeebe:8.3.0
    environment:
    - ZEEBE_LOG_LEVEL=debug
    ports:
    - "26500:26500"
    - "9600:9600"
    networks:
    - zeebe_network
  connector-runtime:
    container_name: connector-runtime
    image: camunda/connectors-bundle:8.3.0
    environment:
    - ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=zeebe:26500
    - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
    - CAMUNDA_CONNECTOR_POLLING_ENABLED=false
    - CAMUNDA_CONNECTOR_WEBHOOK_ENABLED=false
    - SPRING_MAIN_WEB-APPLICATION-TYPE=none
    - OPERATE_CLIENT_ENABLED=false
    depends_on:
    - zeebe
    networks:
    - zeebe_network
    volumes:
    - ./../example-connector/target/example-connector-1.0-SNAPSHOT.jar:/opt/custom/spring-connector.jar
